version: "3.9"

services:
  # database
  db:
    image: postgres
    container_name: postgres
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  # web app
  gunicorn:
    build: .
    container_name: gunicorn-django
    volumes:
      # source files
      - type: bind
        source: .
        target: /smartdoor_host
      # gunicoen unix socket
      - type: volume
        source: gunicorn
        target: /var/run/gunicorn
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    command: >
      sh -c "
        python manage.py migrate
        gunicorn smartdoor_prj.wsgi --bind=unix:/var/run/gunicorn/gunicorn.sock
      "

  # create SSL Certificates
  cert:
    image: paulczar/omgwtfssl
    env_file:
      - .env
    volumes:
      - type: bind
        source: ssl_certs
        target: /certs

  # web server
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - target: 80
        published: 80
      - target: 443
        published: 443
    volumes:
      # .conf file
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
      # gunicorn unix socket
      - type: volume
        source: gunicorn
        target: /var/run/gunicorn
      # static dir
      - type: bind
        source: ./smartdoor_prj/static
        target: /static
      # ssl cert
      - type: bind
        source: ssl_certs
        target: /etc/ssl_cert

    depends_on:
      - gunicorn
      - cert
    restart: always

volumes:
  db_data:
  gunicorn:
