# Generated by Django 3.2.5 on 2022-04-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keymanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='allow_423',
            field=models.BooleanField(null=True, verbose_name='allow 423'),
        ),
        migrations.AlterField(
            model_name='key',
            name='allow_475',
            field=models.BooleanField(null=True, verbose_name='allow 475'),
        ),
        migrations.AlterField(
            model_name='key',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
    ]
