# Generated by Django 3.2.5 on 2022-04-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keymanagement', '0002_auto_20220414_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='idm',
            field=models.CharField(max_length=16, unique=True, verbose_name='idm'),
        ),
    ]
