# Generated by Django 3.2.5 on 2022-04-23 08:14

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keymanagement', '0003_alter_key_idm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='idm',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=16, unique=True, verbose_name='idm'),
        ),
    ]
