# Generated by Django 3.2.5 on 2022-04-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keymanagement', '0004_alter_key_idm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='idm',
            field=models.CharField(max_length=16, unique=True, verbose_name='idm'),
        ),
    ]
